name: entrenador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.2
  flutter_riverpod: ^3.0.2
  go_router: ^16.2.4
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  table_calendar: ^3.0.9
  syncfusion_flutter_calendar: ^31.2.4
  # Agregamos url_launcher aquí porque lo usamos en el código anterior
  url_launcher: ^6.3.0 
  pdf: ^3.10.0
  path_provider: ^2.1.2
  #open_file: ^3.3.2
  http: ^1.2.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Aquí se define la versión de la librería (con indentación)
  flutter_native_splash: ^2.3.10
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0

# CONFIGURACIÓN DE FLUTTER
flutter:
  uses-material-design: true
  assets:
    - assets/

# CONFIGURACIÓN DE LA SPLASH SCREEN
# Esta sección va al nivel raíz (sin espacios a la izquierda), separada de dev_dependencies
flutter_native_splash:
  color: "#1C1C1E"
  image: assets/logo.png
  branding: assets/branding.png
  android_12:
    image: assets/logo.png
    color: "#1C1C1E"